Repository Core-Dynamic-Plus-Labs/SafePlay-Guardian, pull requests merged in 2024-08, with the labels that each got.

#1 Update CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#12 Create code_quality.yml
  .github/workflows/code_quality.yml
Labels: enhancement

#13 Delete .github/workflows/code_quality.yml
  .github/workflows/code_quality.yml
Labels: bug

#16 Database, enhancements, and features
  .gitignore
  app/__init__.py
  app/models.py
  app/routes.py
  app/templates/add_exclusion.html
  app/templates/view_exclusions.html
  requirements.txt
Labels: bug, enhancement
